---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gethconfig-miner
  namespace: default
  labels:
    app: kuberneteth
    name: gethconfig-miner
data:
  gethconfig: |-
    [Eth]
    NetworkId = 1101
    SyncMode = "fast"
    LightPeers = 20
    DatabaseCache = 128
    Etherbase = "0x023e291a99d21c944a871adcc44561a58f99bdbc"
    MinerThreads = 1
    GasPrice = 18000000000
    EnablePreimageRecording = false
    
    [Eth.Ethash]
    CacheDir = "ethash"
    CachesInMem = 2
    CachesOnDisk = 3
    DatasetDir = "/root/.ethash"
    DatasetsInMem = 1
    DatasetsOnDisk = 2
    PowMode = 0
    
    [Eth.TxPool]
    NoLocals = false
    Journal = "transactions.rlp"
    Rejournal = 3600000000000
    PriceLimit = 1
    PriceBump = 10
    AccountSlots = 16
    GlobalSlots = 4096
    AccountQueue = 64
    GlobalQueue = 1024
    Lifetime = 10800000000000
    
    [Eth.GPO]
    Blocks = 10
    Percentile = 50
    
    [Shh]
    MaxMessageSize = 1048576
    MinimumAcceptedPOW = 2e-01
    
    [Node]
    UserIdent = "miner"
    DataDir = "/etc/testnet/miner"
    IPCPath = "/etc/testnet/miner/geth.ipc"
    HTTPHost = "0.0.0.0"
    HTTPPort = 8545
    HTTPCors = ["*"]
    HTTPVirtualHosts = ["*"]
    HTTPModules = ["db", "eth", "net", "web3", "personal", "web3"]
    WSHost = "0.0.0.0"
    WSPort = 8546
    WSModules = ["net", "web3", "eth", "shh"]
    
    [Node.P2P]
    MaxPeers = 25
    NoDiscovery = false
    BootstrapNodes = []
    BootstrapNodesV5 = []
    StaticNodes = []
    TrustedNodes = []
    ListenAddr = ":30303"
    EnableMsgEvents = false
    


