---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitor-deployment
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      name: monitor-deployment
      labels:
        app: kuberneteth
        tier: frontend
        name: monitor-deployment
    spec:
      initContainers:
      - name: monitor-init-container
        image: mmeister/eth-net-intelligence-api
        command: [ "sh" ]
        args:
        - "-cx"
        - "cp -r /eth-net-intelligence-api/* /ethmonitor;
           cp /monitor-configmap/app.json /ethmonitor/app.json;
           sed -i \"s/miner-rpchost/$MINER_SVC_SERVICE_HOST/g\" /ethmonitor/app.json;
           exit 0;"
        volumeMounts:
        - name: monitor-configmap-volume
          mountPath: /monitor-configmap/app.json
          subPath: app.json
          # we need to mount an extra volume to be able to change a value in the configmap
        - name: monitor-config-persistent-storage
          mountPath: /ethmonitor
      containers:
      - name: eth-netstats-container
        image: mmeister/eth-netstats
        ports:
          - containerPort: 3001
        env:
        - name: WS_SECRET
          value: "connectme"
        - name: PORT
          value: "3001"
      - name: eth-net-intelligence-api-container
        image: mmeister/eth-net-intelligence-api
        volumeMounts:
        - name: monitor-config-persistent-storage
          mountPath: /eth-net-intelligence-api/app.json
          subPath: app.json
      volumes:
      - name: monitor-configmap-volume
        configMap:
          name: monitor-config
          items:
          - key: app.json
            path: app.json
      - name: monitor-config-persistent-storage
        hostPath:
          path: /var/lib/docker/ethmonitor
