---
apiVersion: v1
kind: Service
metadata:
  name: miner-svc
  labels:
    app: kuberneteth
    tier: backend
    name: miner-svc
spec:
  selector:
    app: kuberneteth
    tier: backend
  type: NodePort
  ports:
    - name: miner-jsonrpc
      protocol: TCP
      port: 8545
      targetPort: 8545
      nodePort: 30001
    - name: miner-wsrpc
      protocol: TCP
      port: 8546
      targetPort: 8546
    - name: miner-ipc-listen
      protocol: UDP
      port: 30301
      targetPort: 30301
    - name: miner-ipc-discovery
      protocol: TCP
      port: 30303
      targetPort: 30303
      nodePort: 30002

